# -*- coding: utf-8 -*-
"""Resume_screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEP9BXJQzU5BDy02IwYmaLSw1TlRyH2Q

pipe line

Resume PDF → Extract Text → Extract Features → Score → Rank
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

import joblib

data2=pd.read_csv('/content/resume_data.csv')
df=pd.DataFrame(data2)

df.columns = df.columns.str.replace('\ufeff', '', regex=False)

df.info()

df.isnull().sum()

df.fillna("",inplace=True)

df.drop_duplicates(inplace=True)

df.isnull().sum().sum()

df.shape

df.size

df.columns = df.columns.str.strip().str.lower()
print(df.columns.tolist())

df["matched_score"].describe()

df.drop(columns=[
    "address",
    "company_urls",
    "online_links"
], axis=1, inplace=True)

df["resume_text"] = (
    df["skills"] + " " +
    df["positions"] + " " +
    df["responsibilities"] + " " +
    df["degree_names"] + " " +
    df["major_field_of_studies"]
)

df["job_text"] = (
    df["skills_required"] + " " +
    df["educational_requirements"] + " " +
    df["responsibilities.1"]
)

df["combined_text"] = df["resume_text"] + " " + df["job_text"]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=500
)

x = vectorizer.fit_transform(df["combined_text"])
y = df["matched_score"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

x_train.shape

y_train.shape

from sklearn.metrics import mean_squared_error, r2_score
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

df["matched_score"].describe()

print("Train R2:", model.score(x_train, y_train))
print("Test R2:", model.score(x_test, y_test))

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

print("LR R2:", lr.score(x_test, y_test))

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor()
gbr.fit(x_train, y_train)

print("GBR R2:", gbr.score(x_test, y_test))

from sklearn.metrics import mean_absolute_error

print("MAE:", mean_absolute_error(y_test, y_pred))

TfidfVectorizer(max_features=500, ngram_range=(1, 2))

model = RandomForestRegressor(
    n_estimators=50,         # Reduced
    max_depth=20,            # Prevent huge trees
    min_samples_split=2,
    random_state=42,
    n_jobs=-1
)

model.fit(x_train, y_train)

print("Test R2:", model.score(x_test, y_test))

df["label"] = (df["matched_score"] >= 0.75).astype(int)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

clf = RandomForestClassifier(random_state=42)
clf.fit(x_train, df.loc[y_train.index, "label"])

y_pred = clf.predict(x_test)

print(classification_report(
    df.loc[y_test.index, "label"],
    y_pred
))

df["predicted_score"] = model.predict(x)

top_candidates = df.sort_values(
    by="predicted_score",
    ascending=False
)

top_candidates[[
    "job_position_name",
    "predicted_score"
]].head(10)

import joblib

joblib.dump(model, "resume_screening_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print(vectorizer.vocabulary_ is not None)